### ISSUE TITLE
Userspace support for Kotlin/Native 

### ISSUE THREAD

**Issue by advancedwebdeveloper** [aosp-riscv/working-group#15]
Hi.
I am curious if you would define unresolved/undefined blockers, for supporting https://kotlinlang.org/docs/reference/native-overview.html

CC @LepilkinaElena

**Comment by unicornx** [comment]
> Hi.
> I am curious if you would define unresolved/undefined blockers, for supporting https://kotlinlang.org/docs/reference/native-overview.html
> 
> CC @LepilkinaElena

Hi Ivan,
I have little knowledge about the project you mentioned above. This project (aosp-riscv) is targeting to port android on RISC-V. What can we do help for you？

**Comment by advancedwebdeveloper** [comment]
Apparently you can arrange CI workflows, for both Qemu and ASIC, FPGA boards.
As for Kotlin/Native - it was about porting their existing demos (as also as JVM related Kotlin demos, for Aarch64 port of Android) on RISCV64 port of Android.

I wonder where is your roadmap, for existing RISC-V extensions/CPU features and testing reports (Qemu; HiFive's boards; ...).
Some visual content on the coverage of specific Android's kernel features, userspace features would be of help.

**Comment by unicornx** [comment]
We stopped working on this project due to there is another better choice from T-head, <https://github.com/T-head-Semi/aosp-riscv>, just FYI.
