### ISSUE TITLE
emulator for riscv

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/working-group#21]
We need to enable aosp emulator to support riscv64.
 
FYI：aosp 12 supports linux kernel 4.19，5.4， 5.10， I suggest to try with latest 5.10。google kernel repo is located at: https://android.googlesource.com/kernel/common/， you can pick the kernel with tag "android-mainline-5.10".

**Comment by liushuyu** [comment]
# Progress Report on 2021-11-29

## Completed Items

- Initial survey of https://android.googlesource.com/platform/external/qemu/ repository
    - Initial survey showed that the current active branch `emu-master-dev` seems to use a relatively recent `qemu` version and supports RISC-V target
- Test build of the vanilla emulator
   - Some unit test errors were encountered with the vanilla emulator, however the errors did not hinder the actual emulator from being built or run
   - There is a hardcoded list for the targets that should use the new virtual board, `ranchu`: https://android.googlesource.com/platform/external/qemu/+/refs/heads/emu-master-dev/android/emulator/main-emulator.cpp#154

## Actionable Items

- Build a bare-minimum image for the emulator (kernel only, as the other parts of AOSP, are yet to be worked on)
- Test if the emulator runs with the basic image above (smoke test)

**Comment by liushuyu** [comment]
# Progress Report on 2021-11-30

## Previous Results

- A smoke test w/o any image was performed and failed:
    - Investigation shows that the necessary glue-code was not in-place for RISC-V, and the AOSP did not include the Qemu RISC-V target in the emulator.

## Completed Items

- Qemu RISC-V target has been included in the emulator.
- Necessary glue-code has been written to support Android-specific functionalities for the RISC-V target.
    - NOTE: Some educated guesses have been made when adding the support: `RAM_SPLIT_BOUNDARY` has been set to `0x40000000` (4 GB). This assumes that the memory could address up to `0x40000000`. The value was taken from the`aarch64` target.
- Build files and various scripts have been adjusted to accommodate the target addition.

## Task Progress

| Topic | Last Report | This Report | Change | Start Date | End Date |
|--------|---------|--------|--------|--------|-------|
| Initial Survey | 100% | 100%| - | 2021-11-22| 2021-11-27|
| Smoke Test 1 (Arch support) | 0% | 100% | +100%| 2021-11-27 | 2021-11-28 |
| Initial Porting (Arch support) | 0% |  100%|+100% | 2021-11-28 | 2021-11-30 |
| Smoke Test 2 (Boot kernel) | 0% | 0% | - | 2021-11-30 | 2021-12-02 [Projected] |
| Follow-up Porting (Boot kernel) | 0% | 0% | - | 2021-12-02 [Projected] | TBD |
| Smoke Test 3 (Boot GUI) | 0% | 0% | - | TBD | TBD |
| Follow-up Porting (Boot GUI) | 0%|0%| -|TBD|TBD|

### Next up

- Build a bare-minimum image for the emulator (kernel only, probably we could borrow something from T-Head?).
- Test if the emulator runs with the basic image above (Smoke Test 2).

## Risk Assessment

| Risk | Impact [1-5] | Likelihood [0-10] | Score [I*L] | Mitigation |
|----|----|----|----|----|
| Qemu 2 does not work well with RV| 3 | 6 | 18 | Backporting fixes from newer Qemu may help this issue |
| Android-modified Linux kernel does work correctly with RV | 2 | 4 | 8 | Borrowing patches from upstream Linux kernel may resolve the issue|
| Other parts of the Android may not be ready | 3 | 8 | 32 | Using the current Android source tree from T-Head may alleviate this issue |

## Notes

- Task progress and risk assessments are estimations, and should not be treated as accurate projections.
- Date and time are in the Mountain Time timezone.

**Comment by unicornx** [comment]
> # Progress Report on 2021-11-30
> ## Previous Results
> * A smoke test w/o any image was performed and failed:
>   
>   * Investigation shows that the necessary glue-code was not in-place for RISC-V, and the AOSP did not include the Qemu RISC-V target in the emulator.
> 
> ## Completed Items
> * Qemu RISC-V target has been included in the emulator.
> * Necessary glue-code has been written to support Android-specific functionalities for the RISC-V target.
>   
>   * NOTE: Some educated guesses have been made when adding the support: `RAM_SPLIT_BOUNDARY` has been set to `0x40000000` (4 GB). This assumes that the memory could address up to `0x40000000`. The value was taken from the`aarch64` target.
> * Build files and various scripts have been adjusted to accommodate the target addition.
> 
> ## Task Progress
> Topic	Last Report	This Report	Change	Start Date	End Date
> Initial Survey	100%	100%	-	2021-11-22	2021-11-27
> Smoke Test 1 (Arch support)	0%	100%	+100%	2021-11-27	2021-11-28
> Initial Porting (Arch support)	0%	100%	+100%	2021-11-28	2021-11-30
> Smoke Test 2 (Boot kernel)	0%	0%	-	2021-11-30	2021-12-02 [Projected]
> Follow-up Porting (Boot kernel)	0%	0%	-	2021-12-02 [Projected]	TBD
> Smoke Test 3 (Boot GUI)	0%	0%	-	TBD	TBD
> Follow-up Porting (Boot GUI)	0%	0%	-	TBD	TBD
> ### Next up
> * Build a bare-minimum image for the emulator (kernel only, probably we could borrow something from T-Head?).
> * Test if the emulator runs with the basic image above (Smoke Test 2).
> 
> ## Risk Assessment
> Risk	Impact [1-5]	Likelihood [0-10]	Score [I*L]	Mitigation
> Qemu 2 does not work well with RV	3	6	18	Backporting fixes from newer Qemu may help this issue
> Android-modified Linux kernel does work correctly with RV	2	4	8	Borrowing patches from upstream Linux kernel may resolve the issue
> Other parts of the Android may not be ready	3	8	32	Using the current Android source tree from T-Head may alleviate this issue
> ## Notes
> * Task progress and risk assessments are estimations, and should not be treated as accurate projections.
> * Date and time are in the Mountain Time timezone.

Great work done and excellent report, please continue on this.
My comments:
- What's the smoke test you have tried? I would like to know the details, if any test cases are provided or you just use the existing test cases from Google?
- What's the version of kernel you are using? And what's the version of QEMU you are using, I would like to double-check the details. And as I have mentioned, as to kernel version, I hope it is android-mainline-5.10. As to QEMU, I think the latest 6.1 should work for RV.
- Regarding your work on changes, I hope we can see it on github, on develop branch should be fine, we can discuss more details based on code.
- I see you have completed the Initial Survey work, can you please provide a quick report, we have a weekly share days for interns - every Wednesday(15:00-16:00(GMT+08:00). I think the time may be too late for you guys, so I suggest you record (video with your desktop share) at your end and provide it to me, and I can help play it on the on-line meeting, what do you think?
- Regarding the bare-minimum image for the emulator, I would suggest a reference https://zhuanlan.zhihu.com/p/302870095, you can have a look, hope it do help for you.

**Comment by liushuyu** [comment]
> Great work done and excellent report, please continue on this. My comments:
> 
> - What's the smoke test you have tried? I would like to know the details, if any test cases are provided or you just use the existing test cases from Google?
> 

It's a very simple test to see whether the Android emulator could initialize the backend: `./emulator -avd-arch riscv64`. Prior to this report, the initialization process will fail due to the issues described in the report.

> - What's the version of kernel you are using? And what's the version of QEMU you are using, I would like to double-check the details. And as I have mentioned, as to kernel version, I hope it is android-mainline-5.10. As to QEMU, I think the latest 6.1 should work for RV.
> 

I have yet to use a real kernel to boot the emulator since the emulator would crash before a kernel could be loaded.

As for Qemu, Android Emulator uses its own Qemu implementation, which is a heavily modified Qemu 2.x series with many patches backported from some newer versions. Upgrading it does not seem to be practical, since AOSP upstream wrote many virtual peripherals for it (see "Ranchu" virtual board).

> - Regarding your work on changes, I hope we can see it on github, on develop branch should be fine, we can discuss more details based on code.
> 

I am going to do that today after I clean up my patches.

> - I see you have completed the Initial Survey work, can you please provide a quick report, we have a weekly share days for interns - every Wednesday(15:00-16:00(GMT+08:00). I think the time may be too late for you guys, so I suggest you record (video with your desktop share) at your end and provide it to me, and I can help play it on the on-line meeting, what do you think?
> 
> - Regarding the bare-minimum image for the emulator, I would suggest a reference https://zhuanlan.zhihu.com/p/302870095, you can have a look, hope it do help for you.

Thank you! That will help.

**Comment by unicornx** [comment]
> As for Qemu, Android Emulator uses its own Qemu implementation, which is a heavily modified Qemu 2.x series with many patches backported from some newer versions. Upgrading it does not seem to be practical, since AOSP upstream wrote many virtual peripherals for it (see "Ranchu" virtual board).

QEMU 2.x seems a bit old for RISCV，and plus Google adds some peripherals, I would hope these peripherals changes are separated from QEMU core so it would be convenient for porting.  I heard from T-head use a new 3.x QEMU, just FYI.
Have a look at what T-head does should be helpful. Please continue evaluate how much porting work for QEMU and let us know.

**Comment by unicornx** [comment]
@liushuyu as we talked in the call, looks the porting work for android emulator is a bit complicated, so let's suspend this and just use mainline qemu for testing for current work, we may resume this work when we need later.

Please summarize the research work you have till now and prepare a report for us. Thanks.

**Comment by liushuyu** [comment]
# Progress/Closure Report on 2021-12-03

> **NOTE: This project is put on hold indefinitely.**

## Previous Results

- A smoke test w/o kernel image was performed and failed:
    - Investigation shows that the necessary virtual board (`ranchu`) was not implemented for RISC-V.
    - The virtual peripherals are difficult to port since they are tightly integrated and architecture-dependent.
    - The QEMU source code bundled in the emulator is a mishmash mix of QEMU 1, 2 and 3 source files, making porting changes difficult.

## Completed Items

- More tests and patch clean-up were performed.

## Task Progress

| Topic | Last Report | This Report | Change | Start Date | End Date |
|--------|---------|--------|--------|--------|-------|
| Initial Survey | 100% | 100%| - | 2021-11-22| 2021-11-27|
| Smoke Test 1 (Arch support) | 100% | 100% | -| 2021-11-27 | 2021-11-28 |
| Initial Porting (Arch support) | 100% |  100%|- | 2021-11-28 | 2021-11-30 |
| Smoke Test 2 (Boot kernel) | 0% | 100% | +100% | 2021-11-30 | 2021-12-02 |
| Follow-up Porting (Boot kernel) | 0% | 1% | +1% | 2021-12-02 | N/A |
| Smoke Test 3 (Boot GUI) | 0% | 0% | - | N/A | N/A |
| Follow-up Porting (Boot GUI) | 0%|0%| -|N/A|N/A|

### Next up

- After some internal discussion, we decided to put this project **on hold** until further notification.

## Risk Assessment

N/A

## Closing Thoughts

- The AOSP version of QEMU is unfit for the RISC-V port, as the version is too old, and the heavy modifications made by the upstream made the porting work especially difficult.
- Our current goal is to boot the minimum viable system w/o GUI, which could be accomplished better by the latest version of vanilla QEMU.

**Comment by shahzaibk23** [comment]
Hello! I have been working alongside @usmnzain in this project.
We are trying to set up the AOSP sources first, at the moment.
Afterwards we have planned to follow along the Progress Reports to understand the workflow and continue where it is left off :)

**Comment by unicornx** [comment]
> Hello! I have been working alongside @usmnzain in this project. We are trying to set up the AOSP sources first, at the moment. Afterwards we have planned to follow along the Progress Reports to understand the workflow and continue where it is left off :)

FYI, https://github.com/aosp-riscv/working-group/blob/master/docs/howto-setup-build-env.md, a short note introduce how to setup the aosp-riscv (out project based on official AOSP 12.0.0_r3, we have modified it and added some riscv staffs).

**Comment by shahzaibk23** [comment]
@unicornx seems like, I might need rights to access this specific branch.
![image](https://user-images.githubusercontent.com/33006035/145933346-4e257911-9449-43b4-ab60-46e22fdb6c63.png)

**Comment by lazyparser** [comment]
@shahzaibk23 perhaps you need to upload your ssh pubkey to your github ssh settings. All the AOSP repos and branches are public, but the git access are using ssh pubkey auth.

**Comment by shahzaibk23** [comment]
@unicornx I have successfully built the sources of AOSP of the riscv64 branch. Can you guide further on, where shall I begin looking into next.

**Comment by unicornx** [comment]
> @unicornx I have successfully built the sources of AOSP of the riscv64 branch. Can you guide further on, where shall I begin looking into next.

Please read this issue from the top,  liushuyu did some early research on this work and summarized some on this issue page.

As you know we have no riscv hardware on hand, and we need an emulator. On embedded development, QEMU is a good choice and AOSP also has its own emulator, it also uses QEMU inside and Google hacked it heavily and adds lots of work to simulate a handset. The AOSP emulator only supports ARM and X86 family, we need to figure out a way to make it work for RISC-V.

Due to we have many other work in hand, I asked liushuyu terminate this work and switch to other work. When we are on early bring-up work on AOSP, we can use main-line QEMU to help debug/test, but later we definitely need a emulator which can run as a handset and how some mobile UI as you see on ARM.

I believe this work is a relatively separated project, so I hope you can take it up and continue, any questions feel free let me know and we can have discuss on line, on this page or in slack or conf call as you prefer.

I think first thing you may need to go to https://android.googlesource.com/ and download AOSP emulator source code to have  a look first.

**Comment by unicornx** [comment]
I see RISC-V Android Source opened source of qemu just few days ago, https://github.com/riscv-android-src/platform-external-qemu and https://github.com/riscv-android-src/platform-prebuilts-qemu-kernel, you can have a check. Please note it is for aosp 10, I'm not sure if it do help for you on aosp 12, please check it out and let us know.

**Comment by shahzaibk23** [comment]
## Progress Report and Literature/Research Review

Upon what I have studied so far,

- We first require to put support for Ranchu Virtual Board in Platform Prebuilt Qemu Kernel of AOSP 12
- Then we can add target for RISC-V on Platform External QEMU of AOSP 12.

PS: Thank you for the links of AOSP 10 RiscV ports, I will look nto the AOSP 10 ported sources.
I am now starting to look into Ranchu Virtual Board start porting it for AOSP 12.

**Comment by shahzaibk23** [comment]
## Progress Report 06/April/2022

### Emulator Build Process Deep Dive

- `./android/rebuild.sh`  script calls a python script inside `android/build/python/cmake.py`
- The `cmake.py` script launches the cmake from inside the `aemu` directory.

#### AEMU

#### aemu/cmake.py
- function launch()
  - add argument parsers for:
     1. sdk_version
     2. sdk_build_number
     3. config
     4. crash
     5. ........
     6. verbose
     7. asop
  - Configures Logger
  - send AOSP argument value into `set_aosp_root` method to setup the dir for AOSP root.
  - then calls `main` sending all the arguments parsed
- function main(args, target)
  - logs python version
  - Configures the cmake project by calling `configure` method and sending it args and target of current platform as parameters
  - then it build the project with `run` method passing another method `get_build_cmd` sent with args.
  - then finally runs the tests on build, defined in the test arg.
- funtion get_build_cmd
  - return the cmake command with `build` flag defining the out-dir and `target `flag defining the target.
  - the cmake command redirects to `prebuilts/cmake/%s-x86/bin/cmake` where 's' is the platform.
 - function run(cmd) [aemu/process.py]
  - it basically runs the command provided in the parameter on the shell.


The whole process runs the cmake binary file in `prebuilts/cmake/%s-x86/bin/cmake` with the proper flags defining build dir and target and then runs the unit tests on top of the build.

**Comment by shahzaibk23** [comment]
## Progress Report 11/May/2022
I am using the latest updated platform-external-qemu of branch `riscv64-emu-31.3.6-dev`.

I have made the RISC-V specific additions in the following files:
1. avd/generator.cpp  + info.c + util.c + 
2. util/unittests.c
3. android/build/cmake/android.cmake + android/emulator/CMakeLists.txt + android/emulator/main-emulator.cpp + android/scripts/unix/build-qemu-android.sh + android/third_party/chromium/depot_tools/cipd + 
4. android-qemu2-glue/main.cpp
5. CMakeLists.txt
6. default-configs/riscv64-softmmu.mk
7. hw/misc/goldfish_pipe.c + hw/riscv/Makefile.objs + include/hw/riscv/riscv_ranchu.h

And modified these files
1. target/riscv/cpu_bits.h + cpu.h + gdbstub.c + Makefile.objs + helper.c + kvm-stub.c + op_helper.c 
2. vl.c

After these modifiation now that when i am running `android/rebuild.sh` I am getting the following error

```bash
[4707/12619] Building CXX object android/android-emu-base/CMakeFiles/android-emu-base.dir/android/base/files/FileSystemWatcherPosix.cpp.o
[4708/12619] Building CXX object android/android-emu/CMakeFiles/android-emu-shared.dir/android/emulation/ConfigDirs.cpp.o
[4709/12619] Building CXX object android/android-emu-base/CMakeFiles/android-emu-base.dir/android/base/ProcessControl.cpp.o
[4710/12619] Building CXX object android/android-emu/CMakeFiles/android-emu-shared.dir/android/emulation/address_space_host_memory_allocator.cpp.o
[4711/12619] Building CXX object android/android-emu/CMakeFiles/android-emu-shared.dir/android/emulation/goldfish_sync.cpp.o
[4712/12619] Building CXX object android/android-emu/CMakeFiles/android-emu-shared.dir/android/base/async/CallbackRegistry.cpp.o
[4713/12619] Building CXX object android/android-emu/CMakeFiles/android-emu-shared.dir/android/emulation/DmaMap.cpp.o
[4714/12619] Building CXX object android/android-emu/CMakeFiles/android-emu-shared.dir/android/emulation/address_space_graphics.cpp.o
[4715/12619] Building CXX object android/android-emu/CMakeFiles/android-emu-shared.dir/android/emulation/AndroidAsyncMessagePipe.cpp.o
[4716/12619] Building CXX object android/android-emu/CMakeFiles/android-emu-shared.dir/android/emulation/address_space_device.cpp.o
[4717/12619] Building CXX object android/android-emu/CMakeFiles/android-emu-shared.dir/android/emulation/AndroidPipe.cpp.o
[4718/12619] Building CXX object android/android-emu/CMakeFiles/android-emu-shared.dir/android/emulation/control/FilePusher.cpp.o
[4719/12619] Building CXX object android/android-emugl/host/libs/libOpenglRender/vulkan/cereal/CMakeFiles/OpenglRender_vulkan_cereal.dir/common/goldfish_vk_testing.cpp.o
[4720/12619] Building CXX object android/android-emu-base/CMakeFiles/android-emu-base.dir/android/base/system/System.cpp.o
[4721/12619] Building CXX object android/android-emu-base/CMakeFiles/android-emu-base.dir/android/base/files/TarStream.cpp.o
[4722/12619] Building CXX object android/android-emu/android/metrics/proto/CMakeFiles/metrics.dir/studio_stats.pb.cc.o
[4723/12619] Building CXX object android/third_party/perfetto-tracing-only/proto/CMakeFiles/perfetto_trace.dir/perfetto_trace.pb.cc.o
ninja: build stopped: subcommand failed.
Failed to run /aosp/shahzaibk/emu-dev/prebuilts/cmake/linux-x86/bin/cmake --build /aosp/shahzaibk/emu-dev/external/qemu/objs --target install/strip - 1
```

**Comment by unicornx** [comment]
We will directly use emulator from RVI upstream. Close this issue.
