### ISSUE TITLE
ndk for riscv

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/working-group#23]
porting android ndk to risc-v.

This work may affect several repos, I just create one issue here to list the general requirements. After analysis, please separate the work into proper issues on specific repos and raised PR one by one and link every PR to its corresponding repo.

Till as I know, prebuilt/ndk is a final repo we may update. If there is more repos to be created, let me know, thanks.

**Comment by unicornx** [comment]
Now bionic can pass build but has not tested it well. If you want to have a look of bionic,  you can try to build it following up the guide <https://github.com/aosp-riscv/working-group/blob/master/docs/howto-setup-build-env.md> and build it with "mmm bionic --skip-soong-tests".
If you met any issues on bionic, please let me know.

**Comment by unicornx** [comment]
I'm not sure if ndk build will involve many other libraries, if you found too many of them, could you separate the task and we can invite others to join with you.

**Comment by unicornx** [comment]
https://android.googlesource.com/platform/ndk/+/HEAD/docs

**Comment by liushuyu** [comment]
## Progress Report (Summarized)

This is a short progress report on porting effort as of 2021/12/23.

### Affected Repositories

Mainly https://android.googlesource.com/platform/ndk/.

This repository contains various build scripts to build other AOSP platform libraries, including `bionic`, `libc++` and various other projects.

### Encountered Issues

- Numerous build scripts inside the repository assume `x86` or `arm` as the guest architectures. Many of them require modifications
- Build time is a bit long, and there does not seem to have incremental building facilities
- Depends on other ongoing PLCT projects, like `bionic` and LLVM/Clang porting processes
- [Personal] Some IRL stuff at the moment slows down the development

### Current Progress

It's still early to give an estimation. Some of the build scripts have been adapted to RISC-V, but many more are still to go.
A smoke test will be conducted when the process is finished. For example, a possible test might be building the Rust toolchain (RISC-V Android target) with the NDK option enabled.
Another possible test might be compiling a `libc++`-dependent application.

**Comment by unicornx** [comment]
This task is bit huge, please plan and separate it first. Any question please let me know,

**Comment by unicornx** [comment]
We will start the work of aligning with RVI andoird upstream.  T-head said that their ndk for aosp 12 has been open sourced, so we need to switch to RVI android upstream now.
Because we are not a branch that is directly pulled from the RVI-based warehouse, I understand that there will be a period of time. We will synchronize the code on the upstream with our warehouse. After the basic consistency, our warehouse will be directly rebase to the upstream.

**Comment by unicornx** [comment]
close this issue, ndk related work will use that from RVI upstream.
