### ISSUE TITLE
break down ndk task

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/working-group#28]
NDK contains many components and we need to break it down to separated smaller tasks first before continue.

Please refer to https://developer.android.com/ndk/guides/stable_apis and break what we need to port/build for ndk.

The output of this issue is just a report to list how many components we may need to touch,  and early analysis whether we need porting work on it or just building should be fine.

**Comment by liushuyu** [comment]
## Overview

Currently, Android NDK ships with the following prebuilt platform binaries:

```
libaaudio.so   libbinder_ndk.so  libdl.so         libGLESv2.so  libjnigraphics.so  libm.so             libneuralnetworks.so  libstdc++.so  libz.so
libamidi.so    libcamera2ndk.so  libEGL.so        libGLESv3.so  liblog.so          libnativehelper.so  libOpenMAXAL.so       libsync.so
libandroid.so  libc.so           libGLESv1_CM.so  libicu.so     libmediandk.so     libnativewindow.so  libOpenSLES.so        libvulkan.so
```

These binaries come from https://android.googlesource.com/platform/prebuilts/ndk. However, to build them from the source, a complete AOSP workspace is required. A script for building NDK binaries (needs modification to work with RISC-V) is available in `build/soong/scripts/build-ndk-prebuilts.sh` once you have the workspace set up correctly.

## Detailed Origin Information

Below is a breakdown of where all the artifacts coming from and an initial survey of how likely a project needs to be ported:

### [`bionic`](https://android.googlesource.com/platform/bionic)

[:heavy_check_mark: Has a RISC-V Fork](url)
```
libc.so
libdl.so
libm.so
libstdc++.so
```

### [`libnativehelper`](https://android.googlesource.com/platform/libnativehelper)
:white_check_mark: Porting maybe not needed
```
libnativehelper.so
```

### [`external/ANGLE`](https://android.googlesource.com/platform/external/angle)
:white_check_mark: Porting maybe not needed
```
libEGL.so
libGLESv1_CM.so
libGLESv2.so
libGLESv3.so
```

### [`external/zlib`](https://android.googlesource.com/platform/external/zlib)
:white_check_mark: Porting maybe not needed
```
libz.so
```

### [`external/icu`](https://android.googlesource.com/platform/external/icu)
:white_check_mark: Porting maybe not needed
```
libicu.so
```

### [`system/core`](https://android.googlesource.com/platform/system/core)
[:heavy_check_mark: Has a RISC-V Fork](https://github.com/aosp-riscv/platform_system_core)
```
libsync.so
```

### [`system/logging`](https://android.googlesource.com/platform/logging)
:white_check_mark: Porting maybe not needed
```
liblog.so
```

### [`frameworks/wilhelm`](https://android.googlesource.com/platform/frameworks/wilhelm)
:warning: **Porting required**: contains architectural specific logic in symbol maps
**Porting difficulty estimation**: _Very Easy_
```
libOpenMAXAL.so
libOpenSLES.so
```

### [`frameworks/av`](https://android.googlesource.com/platform/frameworks/av)
[:heavy_check_mark: Has a RISC-V Fork](https://github.com/aosp-riscv/platform_frameworks_av)
```
libaaudio.so
libcamera2ndk.so
libmediandk.so (media/ndk)
```

### [`frameworks/base`](https://android.googlesource.com/platform/frameworks/base)
[:heavy_check_mark: Has a RISC-V Fork](https://github.com/aosp-riscv/platform-frameworks-base)
```
libamidi.so (media/native/midi)
```

### [`frameworks/ml`](https://android.googlesource.com/platform/frameworks/ml)
:warning: **Porting required**: contains architectural specific logic in build scripts
**Porting difficulty estimation**: _Easy_
```
libneuralnetworks.so
```

### [`frameworks/native`](https://android.googlesource.com/platform/frameworks/native)
:warning: **Porting required**: contains architectural specific code
**Porting difficulty estimation**: _Hard_
```
libandroid.so
libbinder_ndk.so (libs/binder/ndk)
libjnigraphics.so
libnativewindow.so
libvulkan.so
```

**Comment by unicornx** [comment]
Excellent summary!

Some notes input from my side:
- liblog.so should have been built when I porting bionic, you can get it from output after run "mmm bionic", other so are created but I find they are build with stubs, not real binaries.
- note: for those repos you marked as "Has a RISC-V Fork", currently we just forked them and made some minor changes just to pass make for bionic, we have not really build the components/.so you list under such folders.

Todo:
- I will close this issue bcos we have got the summary already.
- I think the NEXT step is to build these so one by one with the aosp-riscv. I think we just need to make build PASS base on current status. If you have better idea to verify these lib files, let me know.
- We need create separated issue to track for each project (libnativehelper or external/angle), please make your plan and let me know, I will create the issue one by one according to your plan, if you need new repo forked, let me know and I will handle this.
