### ISSUE TITLE
update platform/ndk repo for riscv

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/working-group#29]
https://android.googlesource.com/platform/ndk/ needs to be updated to build ndk for riscv

**Comment by Goomelo** [comment]
Hi unicornx , I've built the aosp on riscv64 but I don't know how I can help you with your work. I am willing to participant in your work. Can you guide me further on?

**Comment by unicornx** [comment]
> Hi unicornx , I've built the aosp on riscv64 but I don't know how I can help you with your work. I am willing to participant in your work. Can you guide me further on?

hi, Goomelo, nice to meet you. You can read <https://github.com/aosp-riscv/working-group/blob/master/README.md> first to learn about us. And if possible, can you introduce yourself, such as what's your experience and what are you interested in. 
Can you open a new issue under https://github.com/aosp-riscv/working-group to discuss more, we can not discuss on this issue page ;)

**Comment by unicornx** [comment]
close this issue due to we will use ndk from RVI upstream.
