### ISSUE TITLE
Seeking an opportunity to join in team's work and keep up with team's pace

### ISSUE THREAD

**Issue by Goomelo** [aosp-riscv/working-group#31]
Hi the aosp_riscv community, currently I am a graduate student major in computer science and really look forward to trying my best to help your work. I have no previous experience in riscv porting things but I have some experience in system programming like building toy emulator which is like a toy thing like qemu based on some tutorials. My interests range broadly from distributed system like communication middleware like DDS(Data Distribution System) and consensus algorithm to computer networks. I am optimistic about the future of riscv and really hope to help you in your work with my best efforts.

**Comment by unicornx** [comment]
> Hi the aosp_riscv community, currently I am a graduate student major in computer science and really look forward to trying my best to help your work. I have no previous experience in riscv porting things but I have some experience in system programming like building toy emulator which is like a toy thing like qemu based on some tutorials. My interests range broadly from distributed system like communication middleware like DDS(Data Distribution System) and consensus algorithm to computer networks. I am optimistic about the future of riscv and really hope to help you in your work with my best efforts.

hello，Goomelo, are you from China?

**Comment by Goomelo** [comment]
> 

yes

**Comment by unicornx** [comment]
> > 
> 
> yes

ok, let's talk by email and not here. My private email-address is unicorn_wang@outlook.com

I will close this issue, then.
