### ISSUE TITLE
bionic unit test: setjmp

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/working-group#33]
We got some failed cases when run bionic-unit-tests-static with setjmp.*:

Segmentation fault

- setjmp.setjmp_smoke
- setjmp._setjmp_smoke
- setjmp._setjmp_signal_mask
- setjmp.setjmp_signal_mask
- setjmp.setjmp_fp_registers
- setjmp.setjmp_stack
- setjmp.bug_152210274

FAILED:

- setjmp.sigsetjmp_0_signal_mask

**Comment by unicornx** [comment]
`bionic/libc/arch-riscv64/bionic/setjmp.S` may have some bugs. Suggest to compare with `https://github.com/riscv-android-src/platform-bionic` and pick up or do catch-up with.

Expected output:
- bug fix with code changes
- run bionic-unit-tests-static with setjmp.* and pass all cases for setjmp
- provide a short report about code analysis for setjmp implementation and code analysis for setjmp testcases, refer to `bionic/tests/setjmp_test.cpp`

**Comment by Goomelo** [comment]
The failed test setjmp.sigsetjmp_0_signal_mask can be passed after some changes on setjmp.S, and I am still working on Segmentation fault on other tests.

**Comment by unicornx** [comment]
> The failed test setjmp.sigsetjmp_0_signal_mask can be passed after some changes on setjmp.S, and I am still working on Segmentation fault on other tests.

could you please provide any root-cause analysis?

**Comment by Goomelo** [comment]
> 
I will work out an analysis and send it to you.

**Comment by Goomelo** [comment]
I will work on this issue and give an analysis report for the bug and the bug fix process in the form of blog and will have some  progress on the bugs in this week. Sorry for some procrastinate.

**Comment by unicornx** [comment]
closed by https://github.com/riscv-android-src/platform-bionic/pull/21 and https://gitee.com/aosp-riscv/platform_bionic/pulls/21
