### ISSUE TITLE
bionic test: stdio & stdio_nofortify

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/working-group#34]
- stdio_nofortify.snprintf_sscanf_inf_nan
- stdio_nofortify.swprintf_swscanf_inf_nan

stdio also has similar failed cases。
- stdio.snprintf_sscanf_inf_nan
- stdio.swprintf_swscanf_inf_nan

NOTE：
- These cases failed also on aosp 10 T-head 
![image](https://user-images.githubusercontent.com/2476165/153814564-70a4fafc-0788-43cb-b748-405118657cfa.png)

- also failed for dynamic link version - bionic-unit-tests

**Comment by unicornx** [comment]
@BroSheng please check it out together with providing a tech report as before, thanks.

**Comment by BroSheng** [comment]
According to the description, this problem seems from bionic test in Android 10. Do you want me to test from branch riscv64-android-10.0.0_dev or riscv64-android-12.0.0_dev? Does this problem still exist in riscv64-android-12.0.0_dev? And how could I reproduce this problem? Thanks.

**Comment by unicornx** [comment]
> According to the description, this problem seems from bionic test in Android 10. Do you want me to test from branch riscv64-android-10.0.0_dev or riscv64-android-12.0.0_dev? Does this problem still exist in riscv64-android-12.0.0_dev? And how could I reproduce this problem? Thanks.

riscv64-android-12.0.0_dev also has the same problem. Please read https://github.com/aosp-riscv/test-riscv/blob/riscv64-android-12.0.0_dev/docs/howto-setup-test-env.md to setup test env, use host method if you have no sudo permission.

**Comment by BroSheng** [comment]
Still investigating. I'll post here once there is any update.

**Comment by BroSheng** [comment]
While investigating, I met an error caused by the path environment. I've already given out the solution and PRed to the document of aosp-riscv/test-riscv. Please see in this [Pull Request](https://github.com/aosp-riscv/test-riscv/pull/1).

**Comment by BroSheng** [comment]
Update: Still analyzing related files.

**Comment by BroSheng** [comment]
Update:
So these errors are related to nan, which is actually not-a-number. I tested several different devices from different architecture and got different values.
I used the C code behind:
```
#include <stdio.h>

int main(){
	double f = 0.0/0.0;
	printf("%f\n", f);
	return 0;
}
```
The results are:
`darwin-arm64`: `nan`
`darwin-x86_64`: `nan`
`linux-x86_64`: `-nan`
`linux-arm64`: `nan`
From our riscv64 qemu, we got `nan`. The errors are caused by comparing nan and -nan and getting the different values. However, I wonder do we need to make the result to be `-nan` since some architecture just doesn't act like this.

**Comment by unicornx** [comment]
> Update: So these errors are related to nan, which is actually not-a-number. I tested several different devices from different architecture and got different values. I used the C code behind:
> 
> ```
> #include <stdio.h>
> #include <math.h>
> 
> int main(){
> 	float f = -nanf("");
> 	printf("%f\n", f);
> 	return 0;
> }
> ```
> 
> The results are: `darwin-arm64`: `nan` `darwin-x86_64`: `nan` `linux-x86_64`: `-nan` `linux-arm64`: `-nan` From our riscv64 qemu, we got `nan`. The errors are caused by comparing nan and -nan and getting the different values.

I have no valuable comments on your question, maybe you can read glibc/musl code for reference or post question to related mail-list?

**Comment by BroSheng** [comment]
Update: This week is a midterm week. More details will be available after this week. Thanks.

**Comment by unicornx** [comment]
close it due to duplicated with https://gitee.com/aosp-riscv/working-group/issues/I5CKA4
