### ISSUE TITLE
libtest_invalid-zero_shdr_table_content.so

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/working-group#47]
Please @CambridgeMjq take work on providing technical report, please refer to sample I provided attached:
[dlopen_invalid_zero_shdr_table_content.md](https://github.com/aosp-riscv/working-group/files/8580904/dlopen_invalid_zero_shdr_table_content.md)

Please @Goomelo take the work on providing programming to implement automatic modifying the file `bionic/tests/prebuilt-elf-files/riscv64/libtest_empty.so`.

**Comment by Goomelo** [comment]
I will work on this.

**Comment by unicornx** [comment]
close this due to no progress
