### ISSUE TITLE
Wanted android-libunwind with support riscv64 for build aapt

### ISSUE THREAD

**Issue by jershell** [aosp-riscv/working-group#50]
I trying rebuild the ubuntu aapt packange for riscv64. The android-libunwind lock me because its unsupported riscv64. Do you know how to resove it? I trying use as it is from official repo unwind, but android version contains thing like this 
```
/* ANDROID support update.*/
blablabla
```
https://android.googlesource.com/platform/external/libunwind/+/ec57b05e0acc7838d2a0f75551a18d28f670692e

**Comment by unicornx** [comment]
![4f7f497532fd6c206581c68c1f32bbd](https://user-images.githubusercontent.com/2476165/172290453-101878c8-f50e-4fa8-91c1-d868a4479005.jpg)

**Comment by unicornx** [comment]
@jershell can I close this issue now?

**Comment by unicornx** [comment]
close this issue due to no response for a long time.
